source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'Warp_Example', :exclusive => true do
  pod 'Warp', :path => '../'
end

target 'Warp_Tests', :exclusive => true do
  pod 'Warp', :path => '../'
end
